AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AlignParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/Void:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/VariableNumber:
  Enabled: false
